language: java

matrix:
  include:
    - jdk: oraclejdk8
    - jdk: oraclejdk9

before_install:
  - sed -i.bak -e 's|http://repo.maven.apache.org/maven2|https://repo.maven.apache.org/maven2|g' $HOME/.m2/settings.xml

install: true

script:
  - ./mvnw clean install
